safe:        false
port:        1337
baseurl:     /
url:         http://localhost:1337
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
markdown:    kramdown
permalink:   date
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

